
 //------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using System;
    public partial class DBSession:CRM11.IRespository.IDBSession
    {
    	CRM11.IRespository.IDepartment _Department;
        public CRM11.IRespository.IDepartment Department 
        { 
        	get
        	{
                if (_Department == null)
                    _Department = new Department();
                return _Department;
        	}
        }
    
    	CRM11.IRespository.IEmployee _Employee;
        public CRM11.IRespository.IEmployee Employee 
        { 
        	get
        	{
                if (_Employee == null)
                    _Employee = new Employee();
                return _Employee;
        	}
        }
    
    	CRM11.IRespository.IEmpRoleRelation _EmpRoleRelation;
        public CRM11.IRespository.IEmpRoleRelation EmpRoleRelation 
        { 
        	get
        	{
                if (_EmpRoleRelation == null)
                    _EmpRoleRelation = new EmpRoleRelation();
                return _EmpRoleRelation;
        	}
        }
    
    	CRM11.IRespository.IPermission _Permission;
        public CRM11.IRespository.IPermission Permission 
        { 
        	get
        	{
                if (_Permission == null)
                    _Permission = new Permission();
                return _Permission;
        	}
        }
    
    	CRM11.IRespository.IRole _Role;
        public CRM11.IRespository.IRole Role 
        { 
        	get
        	{
                if (_Role == null)
                    _Role = new Role();
                return _Role;
        	}
        }
    
    	CRM11.IRespository.IRolePerRelationship _RolePerRelationship;
        public CRM11.IRespository.IRolePerRelationship RolePerRelationship 
        { 
        	get
        	{
                if (_RolePerRelationship == null)
                    _RolePerRelationship = new RolePerRelationship();
                return _RolePerRelationship;
        	}
        }
    
    	CRM11.IRespository.IVipPermssion _VipPermssion;
        public CRM11.IRespository.IVipPermssion VipPermssion 
        { 
        	get
        	{
                if (_VipPermssion == null)
                    _VipPermssion = new VipPermssion();
                return _VipPermssion;
        	}
        }
    
    }
}
