//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission:BaseService<MODEL.Permission>,CRM11.IService.IPermission
    {
    		IRespository.IPermission iSonDal = null;
            public override void SetIDAL()
            {
                iSonDal = base.DBSession.Permission;
    			base.iBaseDal = iSonDal;
            }
    }
}
