//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePerRelationship:BaseService<MODEL.RolePerRelationship>,CRM11.IService.IRolePerRelationship
    {
    		IRespository.IRolePerRelationship iSonDal = null;
            public override void SetIDAL()
            {
                iSonDal = base.DBSession.RolePerRelationship;
    			base.iBaseDal = iSonDal;
            }
    }
}
