//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role:BaseService<MODEL.Role>,CRM11.IService.IRole
    {
    		IRespository.IRole iSonDal = null;
            public override void SetIDAL()
            {
                iSonDal = base.DBSession.Role;
    			base.iBaseDal = iSonDal;
            }
    }
}
